### ISSUE TITLE
Resolve uri

### ISSUE THREAD

**Issue by luckyraul** [puppetlabs/puppetlabs-terraform#18]
## Describe the Bug
```
groups:
  - name: xxx_lb
    targets:
      - _plugin: terraform
        dir: ../xxx
        resource_type: aws_instance.lb
        target_mapping:
          uri: public_ip
```
When I run
```bolt inventory show --targets xxx-lb --debug --detail```
output: 
Command returned successfully
```{"target":"localhost","action":"task","object":"terraform::resolve_reference","status":"success","value":{"value":[{"uri":"xxx.xx.xx.xx"}]}}```

```Did not find config for xxx-lb in inventory```
```
{
  "targets": [
    {
      "name": "xxx-lb",
      "uri": "xxx-lb",
      "alias": [

      ],
```
If I run plan 
```
{"target":"xxx-lb","action":"task","object":null,"status":"failure","value":{"_error":{"kind":"puppetlabs.tasks/connect-error","msg":"Failed to connect to xxx-lb: getaddrinfo: nodename nor servname provided, or not known","details":{},"issue_code":"CONNECT_ERROR"}}}
```
## Expected Behavior
```
{
  "targets": [
    {
      "name": "xxx-lb",
      "uri": "xxx.xx.xx.xx",
      "alias": [

      ],
```

**Comment by donoghuc** [comment]
I would expect:
```
groups:
  - name: xxx_lb
    targets:
      - _plugin: terraform
        dir: ../xxx
        resource_type: aws_instance.lb
        target_mapping:
          uri: public_ip
```
To create a new target for each instance of `aws_instance.lb.public_ip`. If this is not currently working it seems like maybe there is an issue with resolving that data from the statefile. Can you try just running the resolve_reference task (see https://github.com/puppetlabs/puppetlabs-terraform/blob/master/tasks/resolve_reference.json for paramter details).? This might help you understand what is going on.
