### ISSUE TITLE
Fetching passwords from tfstate, need to hide them from bolt logs

### ISSUE THREAD

**Issue by kev-in-shu** [puppetlabs/puppetlabs-terraform#21]
## Use Case
I'm using terraform integration to fetch host information and credentials from newly provisioned servers. But I found out that the resolve_reference task does not return its value as sensitive, hence the values appear in clear in the logs.

```
       - _plugin: terraform
         dir: /path/to/my/terraform/config
         backend: remote
         resource_type: azurerm_windows_virtual_machine
         target_mapping:
           name: name
           config:
             winrm:
               host: private_ip_address
               user: admin_username
               password: admin_password

```

## Describe the Solution You Would Like
Is it possible to make the whole output sensitive, to avoid leaking sensitive information into the logs?
